# Generated by Django 2.2.3 on 2020-02-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190929_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('pdf', models.FileField(upload_to='static/media')),
            ],
        ),
    ]
